#d端口
server:
  port: 8080
spring:
  datasource: #数据源配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.120.202:3306/Alfred_erp?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    druid:
      max-active: 20
      min-idle: 5
      max-wait: 5000
      initial-size: 5
      validation-query: select 1
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        allow:
        deny:
        url-pattern: "/druid/*"
  jackson:
    date-format: yyyy:MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 47.93.120.202
    port: 6378
    jedis:
      pool:
        max-active: 20
        max-idle: 8
        min-idle: 0
        max-wait: 2000
#shiro的配置
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  login-url: /index.html
  unauthorized-url: /unauthorized.html
  anon-urls:
    - /**
    - /index.html*
    - /login/login*
    - /resources/**
  logout-url: /login/logout*
  authc-urls:
#    - /**



#mybatisplus的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*/*Mapper.xml

